### PR TITLE
Do not use "dev" domain

### PR DESCRIPTION
**Pull request by asmacdo**
Since this is a real domain, it causes problems.

### CODE REVIEW

**Comment by dralley** [comment]
Why not remove "dev" entirely?  Or use "pulp3dev"?

**Comment by Ichimonji10** [comment]
Fun fact: there are no top-level domains reserved for private use. `.dev` can cause problems. So can `.pulp3`. Anything put in there can cause problems.

My best recommendation is to use a single word for the host name. Something like `localhost` or `pulp3`. The benefit of single-word host names is that (properly configured) DNS resolvers won't forward lookups for them to the outside world.

**Comment by daviddavis** [comment]
I'm 👍 on using a single-word hostname but just a heads up that we probably want to fix this first:

https://pulp.plan.io/issues/3556

**Comment by Ichimonji10** [comment]
In my local testing, I've worked around that by placing IP addresses in my `~/.config/pulp_smash/*.json` files.

**Comment by Ichimonji10** [comment]
I believe "localhost" is exempt from Django's ban on single-word hostnames. That has obvious implications for remote access.

**Comment by daviddavis** [comment]
Yes, [localhost is indeed exempt](https://github.com/django/django/blob/master/django/core/validators.py#L93).

https://pulp.plan.io/issues/3556 is fixed so I think we just need to update this PR to use a single-word word hostname (e.g. `pulp3` or `pulp3dev`) and we're good?

**Comment by Ichimonji10** [comment]
I test Pulp 3 with single-word host names all the time now, without encountering any issues at all.

**Comment by dparalen** [comment]
I've rebased and updated the PR now I have to provide username:password on the requests (dunno why):
```
[1]+ pulp-manager runserver pulp3:8000 &
(pulp) [vagrant@pulp3 pulp]$ http POST http://pulp3:8000/pulp/api/v3/repositories/ name=bar
Forbidden: /pulp/api/v3/repositories/
pulp: django.request:WARNING: Forbidden: /pulp/api/v3/repositories/
[20/Sep/2018 07:53:01] "POST /pulp/api/v3/repositories/ HTTP/1.1" 403 58
HTTP/1.1 403 Forbidden
Allow: GET, POST, HEAD, OPTIONS
Content-Length: 58
Content-Type: application/json
Date: Thu, 20 Sep 2018 07:53:01 GMT
Server: WSGIServer/0.2 CPython/3.6.6
Vary: Accept, Cookie
X-Frame-Options: SAMEORIGIN

{
    "detail": "Authentication credentials were not provided."
}

(pulp) [vagrant@pulp3 pulp]$ http POST http://admin:admin@pulp3:8000/pulp/api/v3/reposi
tories/ name=bar
[20/Sep/2018 07:53:28] "POST /pulp/api/v3/repositories/ HTTP/1.1" 201 206
HTTP/1.1 201 Created
Allow: GET, POST, HEAD, OPTIONS
Content-Length: 206
Content-Type: application/json
Date: Thu, 20 Sep 2018 07:53:28 GMT
Location: /pulp/api/v3/repositories/2/
Server: WSGIServer/0.2 CPython/3.6.6
Vary: Accept, Cookie
X-Frame-Options: SAMEORIGIN

{
    "_href": "/pulp/api/v3/repositories/2/",
    "_latest_version_href": null,
    "_versions_href": "/pulp/api/v3/repositories/2/versions/",
    "created": "2018-09-20T07:53:28.395551Z",
    "description": "",
    "name": "bar",
    "notes": {}
}

(pulp) [vagrant@pulp3 pulp]$ 
```
Thoughts?

**Comment by daviddavis** [comment]
@dparalen does 'pulp3' resolve to 127.0.0.1? Try pinging that domain. We only set up [the netrc file](https://github.com/pulp/devel/blob/master/ansible/roles/pulp-user/files/netrc) for localhost and 127.0.0.1 so it's possible that maybe pulp3 for you resolves to something like `::1`.

**Comment by dparalen** [comment]
@daviddavis thanks, that's indeed the case: pulp3 doesn't resolve to localhost.
Btw how do I push to this same PR? I'd like to prevent loosing the conversation with my update to this PR.

```
[vagrant@pulp3 ~]$ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
33: eth0@if34: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:2/64 scope link
       valid_lft forever preferred_lft forever
[vagrant@pulp3 ~]$ cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      pulp3
[vagrant@pulp3 ~]$ cd devel/devel/
[vagrant@pulp3 devel]$ git grep netrc
ansible/roles/pulp-user/tasks/main.yml:  - name: Create ~/.netrc if not already present
ansible/roles/pulp-user/tasks/main.yml:      src: files/netrc
ansible/roles/pulp-user/tasks/main.yml:      dest: "{{ pulp_user_home }}/.netrc"
[vagrant@pulp3 devel]$ cat ~/.netrc
machine localhost
login admin
password admin

machine 127.0.0.1
login admin
password admin
```

**Comment by daviddavis** [comment]
@milan, you can open a PR against [asmacdo's fork](https://github.com/asmacdo/devel). Make sure to use the `asmacdo-patch-1` branch.

**Comment by dparalen** [comment]
@daviddavis thanks! @asmacdo I can't see `asmacdo-patch-1` on your fork but saw it on @pavelpicka 's fork... it's a rebase so there's a merge conflict tho. Probably I should create a fresh PR after all?

**Pull request closed without merging**
