### PR TITLE
Use hyphens for Pulp3' system units name

### PR DESCRIPTION
**Pull request by mdellweg**
re #4187
https://pulp.plan.io/issues/4187

### CODE REVIEW

**Comment by asmacdo** [comment]
I had suggested to @ipanova that this isn't necessary, but since we haven't deprecated this repo yet, LGTM

**Comment by mdellweg** [comment]
Hey, i was only distracted for a few seconds... I wanted to ping her.

Ähm, well until pulplift is fully working, and announced to do so we must keep this working. (At least i still use it.)

**Comment by daviddavis** [comment]
Did this PR not fix the problem? https://github.com/pulp/devel/pull/212

**Comment by mdellweg** [comment]
It looks quite similar. Need to check.

**Comment by mdellweg** [comment]
It is bit-wise exactly the same. (Should pull more often.) Closing here.

**Pull request closed without merging**
