### PR TITLE
Provisioning updates for Pulp 3

### PR DESCRIPTION
**Pull request by seandst**
- Example Vagrantfile updated with changes from pulp 2
- modified the gitignore to ignore different Vagrantfiles and
  all playbook retry files from ansible.
- Playbook updated to use the dev_requirements file intoduced in
  https://github.com/pulp/pulp/pull/2888

### CODE REVIEW

**Comment by dralley** [comment]
"vagrant up" fails because dev_requirements.txt is missing.  Did you forget to push it?

**Comment by seandst** [comment]
In working with the new pulp_file plugin, I've discovered an annoyance with migrations that makes me think we just should make them until we decide the data model is good. I'm not sure if I'll open a separate issue for this, or just roll it up into this "fix 3.0-dev vagrant" omnibus to address this, though.

**Comment by bmbouter** [comment]
@seandst regarding the migrations +1 to not committing them until later in the project. Feel free to fix/modify however you see fit.

**Comment by seandst** [comment]
I'm finding a few things that I'd like to fix as part of the process of documenting how plugins should work with platform and be laid out. I think I'll merge this for now, and file/fix issues as appropriate. I think the migrations problem is something I should fix as part of my PRs to stub out the file plugin, since they're required for it to work, and the other issues we can fix in the normal sprint cycle. They're annoying, but not totally breaking.

**Pull request merged**
